### ISSUE TITLE
TO-DO ActionTraction (small tasks)

### ISSUE THREAD

**Issue by MaddyKapfhammer** [MaddyKapfhammer/ActionTraction#12]
Here is the list of everything that needs to be finished for ActionTraction. Most of these are simple additions, that should not take long.

- [ ] Enhancement of the CLI (add progress statements etc.)
- [x] Rewrite column headings for pandas dataframes (all with snake-case conventions)
- [x] Add linting (black, flake8, pydocstyle, pylint)
- [x] Add testing + coverage badge
- [ ] Add types to all function parameters
- [x] Comment functions in `file_contents_analysis.py`
- [x] Create tool logo
- [x] Documentation of tool
- [x] Convert dataframes to `.csv` files
- [x] Add continuous integration
- [x] Add Continuous integration build badge
- [x] Complete features related to commits of entire repository (files changed, collaborators)
- [ ] Determine correctness/validity of complexity metrics (use existing repos, determine complexity and then see if they seem correct)
- [ ] RQ's with clear necessary statistics, and expectations for graphical representation
- [x] Create clear convention for file naming, and rename files as necessary
- [x] Tool descrption
